//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class AVPlayerItem,IGVideoPlayerTargetView,NSURL;

@interface IGFeedVideoPlayer
{

    AVPlayerItem *_streamingPlayerItem;
   
    IGVideoPlayerTargetView *_videoTargetView;
    NSURL *_URL;
    NSURL *_loadingURL;
}


@property(retain, nonatomic) NSURL *loadingURL; // @synthesize loadingURL=_loadingURL;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) IGVideoPlayerTargetView *videoTargetView; // @synthesize
@property(retain, nonatomic) AVPlayerItem *streamingPlayerItem; // @synthesize streamingPlayerItem=_streamingPlayerItem;

- (void)play;

- (id)player;


@end

