//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGFeedItemVideoView;

@interface IGFeedItemVideoCell
{
    IGFeedItemVideoView *_videoView;
}


@property(retain, nonatomic) IGFeedItemVideoView *videoView; // @synthesize videoView=_videoView;

- (void)feedItemVideoViewDidDoubleTapToLike:(id)arg1;


@end

