//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGFeedVideoPlayer;

@interface IGFeedItemVideoView : UIView
{
    UIView *_videoView;

    
    IGFeedVideoPlayer *_player;
}

@property(retain, nonatomic) IGFeedVideoPlayer *player; // @synthesize player=_player;


- (id)photoImageView;


@end

